services:
  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api-server
      - batch-server

  api-server:
    build:
      context: ./Backend/naratil
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-api:3306/apidb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
    depends_on:
      - mysql-api
      - mongo

  batch-server:
    build:
      context: ./Backend/batch
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-batch:3306/batchdb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      FASTAPI_URL: http://fastapi:8000
    depends_on:
      - mysql-batch
      - mongo
      - fastapi

  fastapi:
    build:
      context: ./AI/nara_ai
    ports:
      - "8000:8000"

  mysql-api:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apidb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_api_data:/var/lib/mysql

  mysql-batch:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: batchdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_batch_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_api_data:
  mysql_batch_data:
  mongo_data:
